Blog/Controllers/BiografiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Data;
using Blog.Data.DAL;
using Blog.Migrations;
using Blog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations.Internal;
using Biografia = Blog.Models.Biografia;

namespace Blog.Controllers
{
    public class BiografiaController : Controller
    {

        private readonly BlogContext _context;


        public BiografiaController(BlogContext context)
        {
            _context = context;

        }



        public async Task<IActionResult> Index()
        {
            return View(await _context.Biografias.OrderBy(c => c.BiografiaId).ToListAsync());
        }


        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var biografia = await _context.Biografias.SingleOrDefaultAsync(m => m.BiografiaId == id);

            if (biografia == null)
            {
                return NotFound();
            }

            ViewBag.Biografias = new SelectList(_context.Biografias.OrderBy(b => b.Texto), "BiografiaId", "Texto", biografia.BiografiaId);

            return View(biografia);




        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long? id, [Bind("BiografiaId, Texto")] Biografia biografia)
        {
            if (id != biografia.BiografiaId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(biografia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiografiaExists(biografia.BiografiaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(biografia);
        }


        private bool BiografiaExists(long? id)
        {
            return _context.Biografias.Any(e => e.BiografiaId == id);
        }



    }
}

Blog/Controllers/MateriaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using Blog.Data;
using Blog.Data.DAL;
using Blog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;


namespace Blog.Controllers
{
    public class MateriaController : Controller
    {
        private readonly BlogContext _context;
        private readonly MateriaDAL materiaDAL;
        private IHostingEnvironment hostingEnvironment;
        

        public MateriaController(BlogContext context, IHostingEnvironment hostingEnvironment)
        {
            this._context = context;
            materiaDAL = new MateriaDAL(context);
            this.hostingEnvironment = hostingEnvironment;
          
        }
              

        public async Task<IActionResult> Index(string Pesquisa, int Pagina = 1)
        {
            var materiasPesquisa = from m in _context.Materias select m;

            if (!String.IsNullOrEmpty(Pesquisa))
            {
                materiasPesquisa = materiasPesquisa.Where(s => s.Texto.Contains(Pesquisa));
            }

            return View(await materiasPesquisa.ToPagedListAsync(Pagina, 3));
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Titulo, Autor, Resumo, Texto")] Materia materia, IFormFile foto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var stream = new MemoryStream();
                    await foto.CopyToAsync(stream);
                    materia.Foto = stream.ToArray();
                    materia.FotoMimeType = foto.ContentType;
                    await materiaDAL.GravarMateria(materia);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            return View(materia);
        }


        public async Task<IActionResult> MateriaCompleta(long? id)
        {
            return await ObterMateriaVisaoPorId(id);
        }

        [Authorize]
        public async Task<IActionResult> Edit(long? id)
        {
            return await ObterMateriaVisaoPorId(id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(long? id, [Bind("MateriaID, Titulo, Autor, Resumo, Texto")]Materia materia, IFormFile foto, string chkRemoverFoto)
        {
            if(id != materia.MateriaID)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var stream = new MemoryStream();
                if (chkRemoverFoto != null)
                {
                    materia.Foto = null;
                }
                else
                {
                    await foto.CopyToAsync(stream);
                    materia.Foto = stream.ToArray();
                    materia.FotoMimeType = foto.ContentType;
                }


                try
                {
                    
                    await materiaDAL.GravarMateria(materia);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await MateriaExists(materia.MateriaID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(materia);
        }

        [Authorize]
        public async Task<IActionResult> Delete(long? id)
        {
            return await ObterMateriaVisaoPorId(id);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(long? id)
        {
            var materia = await materiaDAL.EliminarMateriaPorId((long)id);
            TempData["Message"] = "Materia " + materia.Titulo.ToUpper() + " Foi Removida";
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> MateriaExists(long? id)
        {
            return await materiaDAL.ObterMateriaPorId((long)id) != null;

        }

        public async Task<IActionResult> ObterMateriaVisaoPorId(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var materia = await materiaDAL.ObterMateriaPorId((long) id);

            if (materia == null)
            {
                return NotFound();
            }
            return View(materia);
        }

        public async Task<FileContentResult> GetFoto(long id)
        {
            Materia materia = await materiaDAL.ObterMateriaPorId(id);
            if (materia != null)
            {
                return File(materia.Foto, materia.FotoMimeType);
            }

            return null;
        }


       
    }
}

Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>


    <environment include="Development">


        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/css/site.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!-- Just an image -->
                
                    <a class="navbar-brand" asp-controller="Biografia" asp-action="Index">
                        <img src="~/Imagens/flavio.jpg" width="30" height="30" alt="" loading="lazy">
                    </a>
              
                
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />



                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Materia" asp-action="Index">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Biografia" asp-action="Index">Sobre</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Blog Desenvolvido por <a asp-area="" asp-controller="Biografia" asp-action="Index">Flávio Landim</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>